---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:

---
kind: pipeline
type: docker
name: notification

steps:
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: 635081347:AAEA56jjuoG3QokgTPb7URrDDJBbBDl1VVc
      to: 595059757

depends_on:
  - arm64
