version: "2.1"

services:
  ipam:
    image: mhzawadi/phpipam:dev
    ports:
      - "80:80"
    links:
      - mysql
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=phpipam
      - MYSQL_USER=phpipam
      - MYSQL_PASSWORD=phpipamadmin
    volumes:
      - /Users/matt/data/phpipam:/var/lib/mysql
